# This is a basic workflow to help you get started with Actions
name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.4.11
      with: 
        hugo-version: 'latest'
    
    - name: New Hugo Blog Site
      run: hugo new site Blog

    - name: Move File
      run: |
        mv -f content Blog
        mv -f static Blog
        mv -f config.toml Blog
    
    - name: Checkout Theme
      uses: actions/checkout@v2
      with:
        repository: matsuyoshi30/harbor
        path: Blog/themes/harbor

    - name: Build
      working-directory: ./Blog
      run: hugo --minify

    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.0.9
      env: 
        SSH_PRIVATE_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        ARGS: "-avz --delete"
        SOURCE: "./Blog/public"
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.USER }}
        REMOTE_PORT: "22"
        TARGET: ${{ secrets.BLOG_PATH }}
